use_frameworks!

platform :ios, '11.0'

target 'TealiumSKAdNetwork_Example' do
  pod 'TealiumSKAdNetwork', :path => '../'

  target 'TealiumSKAdNetwork_Tests' do
    inherit! :search_paths

    
  end
end
