use_frameworks!

platform :ios, '11.0'

target 'TealiumSKAdNetwork_Example' do
  pod 'TealiumSKAdNetwork', :path => '../'
  pod 'tealium-swift/Lifecycle'
  pod 'tealium-swift/Collect'
  
  target 'TealiumSKAdNetwork_Tests' do
    inherit! :search_paths
    
    
  end
end
