use_frameworks!

platform :ios, '11.0'

target 'TealiumSKAdNetwork_Example' do
  pod 'TealiumSKAdNetwork', :path => '../'
  pod 'tealium-swift/Lifecycle', :path => '../../tealium-swift'
  pod 'tealium-swift/Collect', :path => '../../tealium-swift'
  pod 'tealium-swift/RemoteCommands', :path => '../../tealium-swift'
  
  target 'TealiumSKAdNetwork_Tests' do
    inherit! :search_paths
    
    
  end
end
